apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: py-nov21-artifactory-gitops
  description: This is GitOps manifest for py-nov21-artifactory   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: py-nov21-artifactory
    backstage.io/kubernetes-id: py-nov21-artifactory 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: py-nov21-artifactory   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:py-nov21-artifactory
